image: ghcr.io/fxgst/icp-dev-env:release
tasks:
  - init: |
      export PATH="$HOME/bin:$PATH"
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      cp /pocket-ic ./src/icp_hello_world_rust_backend
      npm install &
      dfx start --background --clean

vscode:
  extensions:
    - dfinity-foundation.vscode-motoko
    - tamasfe.even-better-toml
    - rust-lang.rust-analyzer

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
  - name: Dev Server
    port: 3000
    visibility: public
    onOpen: open-browser
